version: '3.3'
services:
  BACKEND:
    image: momo5ms1/validationdevops:latest
    volumes:
      - ./app:/app
    ports:
      - 8089:8089
    depends_on:
      - MYSQL-DATABASE
    networks:
      - mynetwork
  MYSQL-DATABASE:
    image: mysql:8.0
    environment:

      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - mynetwork
volumes:
  mysql_data:
    
networks:
  mynetwork:
    driver: bridge