version: '3.3'

services:

  SonarQube:

    image: sonarqube:latest

    ports:

      - "9000:9000"

  Nexus:

   image: sonatype/nexus3

   ports:

     - "8081:8081"

   volumes:

    - ./nexus/data:/nexus-data