version: '3.8'
services:
  SonarQube:
    image: sonarqube:latest
    ports:
      - "9000:9000"

  Nexus:
   image: sonatype/nexus3
   ports:
     - "8081:8081"
   volumes:
    - ./nexus/data:/nexus-data
  DB-TEST:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: root

    ports:
      - 3307:3306
    volumes:
      - ./data:/var/lib/mysql